### ISSUE TITLE
Usage with stationary camera

### ISSUE THREAD

**Issue by crlz182** [amy-tabb/RWHEC-Tabb-AhmadYousef#7]
Hello,

I have successfully used your tool for eye-in-hand calibration. I also have another external camera that I would like to calibrate wrt the robot's base. This means attaching the checkerboard at the endeffector and moving the robot in front of the stationary camera. Is this even possible with this tool? The transformations in Fig. 1 of the paper would not have the same meaning anymore. So I am not sure if it's still possible to use your code.

**Comment by amy-tabb** [comment]
Yes, it is possible to use the AX=ZB formulation.  You need to reverse some of meanings of the transformations. See this image, which is rough, but I hope you get the idea.  Write back if not!

![eye-on-stand](https://user-images.githubusercontent.com/25328047/173593490-31668edc-b76c-4a51-b790-915241f4162a.jpg)
