### ISSUE TITLE
question about calibration lidar with GPS/imu in a car

### ISSUE THREAD

**Issue by HeXu1** [amy-tabb/RWHEC-Tabb-AhmadYousef#8]
Hi, Dr Amy, thanks for your great work.
I have read your paper about AX=ZB calibration problem. I want calibrate lidar and imu in a moving car with trajectory about them. it seems the same problem with your work.So i have some questions to ask.
1) do your think think your solution can fix the problem about my calibration case, if not, what‘s the problem. I tried to calibrate with some AX=BX solution ,but translation is not good.may be the Parallel rotation axis affect it? 
2) And i’m so shamed to ask can you open the seven compared methods code mentioned in your paper, thanks a lot.

**Comment by amy-tabb** [comment]
Hello, 

Apologies, I am just getting this message. A colleague has done some work on modeling lidar - camera calibration using AX=ZB.
[Paper](https://mdpi-res.com/d_attachment/sensors/sensors-17-02346/article_deploy/sensors-17-02346-v2.pdf?version=1508144136).

There is also Kalibr, which calibrates imus and cameras [GH](https://github.com/ethz-asl/kalibr).

2. I don't have those methods open for now, however Mili Shah has implementations for many of them [website](http://faculty.cooper.edu/mili/Calibration/index.html)
Best A

**Comment by HeXu1** [comment]
ok ,thanks a lot!
