### ISSUE TITLE
Querry re datasets

### ISSUE THREAD

**Issue by cmower** [amy-tabb/RWHEC-Tabb-AhmadYousef#9]
Hi, great work and many thanks for open-sourcing the dataset!

I wanted to quickly clarify a few things re the data. Currently I am just looking at `DS1.zip` and `DS1_write_0.zip`.

1. The transform matrices in `robot_cali.txt` (in `DS1.zip`) represent the transform of the end-effector with respect to the base, `B` in the notation of your paper? I.e. given the robot joint angles, the transforms are computed from the forward kinematics?
2. The transform matrices in `DS1_write_0/DS1_revised/camera_results0/details.txt` (in `DS1_write_0.zip`) are the transforms from the camera to the world, i.e. `A` in the notation of your paper?
3. The translations for all transforms are given in millimetres?

Thanks in advance!

**Comment by amy-tabb** [comment]
Hello, Thanks!

> `Currently I am just looking at DS1.zip and DS1_write_0.zip.`

1. Yes, you are correct.  Those matrices represent `B`.  The transforms come from the robot encoder, which I assume uses forward kinematics, but whose code is closed. 
1. Yes, you are correct that these are the `A` matrices.
1. Yes translation scale is in millimeters.

An image just to remind myself : )

![repository-open-graph-template](https://user-images.githubusercontent.com/25328047/232864181-9f95f7fa-711a-4429-940c-06ebca8dc1d3.png)

I'm just now figuring out how to see all the issues for repos I own, apologies for the delay.

**Comment by cmower** [comment]
Great, no problem @amy-tabb, many thanks!
